Items = new Mongo.Collection('items');

Items.allow({
  insert: function (userId, doc) {
    return userId && _.contains(doc.owners, userId);
  },
  update: function (userId, doc) {
    return userId && _.contains(doc.owners, userId);
  },
  remove: function (userId, doc) {
    return userId && _.contains(doc.owners, userId);
  },
  fetch: ['owners']
});

var ItemsSchema = new SimpleSchema({
  name: {
    type: String,
    label: 'Button name',
  },
  url: {
    type: SimpleSchema.RegEx.Url,
    label: 'Button Url'
  },
  icon: {
    type: String,
    label: 'Button icon',
    optional: true,
    allowedValues: ['alarm', 'alarm slash', 'alarm outline', 'alarm slash outline', 'at', 'browser', 'bug', 'calendar outline', 'calendar', 'cloud', 'comment', 'comments', 'comment outline', 'comments outline', 'copyright', 'dashboard', 'dropdown', 'external square', 'external', 'eyedropper', 'feed', 'find', 'heartbeat', 'history', 'home', 'idea', 'inbox', 'lab', 'mail', 'mail outline', 'mail square', 'map', 'options', 'paint brush', 'payment', 'phone', 'phone square', 'privacy', 'protect', 'search', 'setting', 'settings', 'shop', 'sidebar', 'signal', 'sitemap', 'tag', 'tags', 'tasks', 'terminal', 'text telephone', 'ticket', 'trophy', 'wifi', 'adjust', 'add user', 'add to cart', 'archive', 'ban', 'bookmark', 'call', 'call square', 'cloud download', 'cloud upload', 'compress', 'configure', 'download', 'edit', 'erase', 'exchange', 'external share', 'expand', 'filter', 'flag', 'flag outline', 'forward mail', 'hide', 'in cart', 'lock', 'pin', 'print', 'random', 'recycle', 'refresh', 'remove bookmark', 'remove user', 'repeat', 'reply all', 'reply', 'retweet', 'send', 'send outline', 'share alternate', 'share alternate square', 'share', 'share square', 'sign in', 'sign out', 'theme', 'translate', 'undo', 'unhide', 'unlock alternate', 'unlock', 'upload', 'wait', 'wizard', 'write', 'write square', 'announcement', 'birthday', 'help', 'help circle', 'info', 'info circle', 'warning', 'warning circle', 'warning sign', 'child', 'doctor', 'handicap', 'spy', 'student', 'user', 'users', 'female', 'gay', 'heterosexual', 'intergender', 'lesbian', 'male', 'man', 'neuter', 'non binary transgender', 'transgender', 'other gender', 'other gender horizontal', 'other gender vertical', 'woman', 'grid layout', 'list layout', 'block layout', 'zoom', 'zoom out', 'resize vertical', 'resize horizontal', 'maximize', 'crop', 'anchor', 'bar', 'bomb', 'book', 'bullseye', 'calculator', 'checkered flag', 'cocktail', 'diamond', 'fax', 'fire extinguisher', 'fire', 'gift', 'leaf', 'legal', 'lemon', 'life ring', 'lightning', 'magnet', 'money', 'moon', 'plane', 'puzzle', 'rain', 'road', 'rocket', 'shipping', 'soccer', 'suitcase', 'sun', 'travel', 'treatment', 'world', 'asterisk', 'certificate', 'circle', 'circle notched', 'circle thin', 'crosshairs', 'cube', 'cubes', 'ellipsis horizontal', 'ellipsis vertical', 'quote left', 'quote right', 'spinner', 'square', 'square outline', 'add circle', 'add square', 'check circle', 'check circle outline', 'check square', 'checkmark box', 'checkmark', 'minus circle', 'minus', 'minus square', 'minus square outline', 'move', 'plus', 'plus square outline', 'radio', 'remove circle', 'remove circle outline', 'remove', 'selected radio', 'toggle off', 'toggle on', 'area chart', 'bar chart', 'camera retro', 'newspaper', 'film', 'line chart', 'photo', 'pie chart', 'sound', 'angle double down', 'angle double left', 'angle double right', 'angle double up', 'angle down', 'angle left', 'angle right', 'angle up', 'arrow circle down', 'arrow circle left', 'arrow circle outline down', 'arrow circle outline left', 'arrow circle outline right', 'arrow circle outline up', 'arrow circle right', 'arrow circle up', 'arrow down', 'arrow left', 'arrow right', 'arrow up', 'caret down', 'caret left', 'caret right', 'caret up', 'chevron circle down', 'chevron circle left', 'chevron circle right', 'chevron circle up', 'chevron down', 'chevron left', 'chevron right', 'chevron up', 'long arrow down', 'long arrow left', 'long arrow right', 'long arrow up', 'pointing down', 'pointing left', 'pointing right', 'pointing up', 'toggle down', 'toggle left', 'toggle right', 'toggle up', 'desktop', 'disk outline', 'file archive outline', 'file audio outline', 'file code outline', 'file excel outline', 'file', 'file image outline', 'file outline', 'file pdf outline', 'file powerpoint outline', 'file text', 'file text outline', 'file video outline', 'file word outline', 'folder', 'folder open', 'folder open outline', 'folder outline', 'game', 'keyboard', 'laptop', 'level down', 'level up', 'mobile', 'power', 'plug', 'tablet', 'trash', 'trash outline', 'barcode', 'css3', 'database', 'fork', 'html5', 'openid', 'qrcode', 'rss', 'rss square', 'server', 'empty heart', 'empty star', 'frown', 'heart', 'meh', 'smile', 'star half empty', 'star half', 'star', 'thumbs down', 'thumbs outline down', 'thumbs outline up', 'thumbs up', 'backward', 'eject', 'fast backward', 'fast forward', 'forward', 'music', 'mute', 'pause', 'play', 'record', 'step backward', 'step forward', 'stop', 'unmute', 'video play', 'video play outline', 'volume down', 'volume off', 'volume up', 'building', 'building outline', 'car', 'coffee', 'emergency', 'first aid', 'food', 'h', 'hospital', 'location arrow', 'marker', 'military', 'paw', 'space shuttle', 'spoon', 'taxi', 'tree', 'university', 'columns', 'sort alphabet ascending', 'sort alphabet descending', 'sort ascending', 'sort content ascending', 'sort content descending', 'sort descending', 'sort', 'sort numeric ascending', 'sort numeric descending', 'table', 'align center', 'align justify', 'align left', 'align right', 'attach', 'bold', 'copy', 'cut', 'font', 'header', 'indent', 'italic', 'linkify', 'list', 'ordered list', 'outdent', 'paragraph', 'paste', 'save', 'strikethrough', 'subscript', 'superscript', 'text height', 'text width', 'underline', 'unlink', 'unordered list', 'dollar', 'euro', 'lira', 'pound', 'ruble', 'rupee', 'won', 'shekel', 'yen', 'american express', 'discover', 'google wallet', 'mastercard', 'paypal card', 'paypal', 'stripe', 'visa', 'adn', 'android', 'angellist', 'apple', 'behance', 'behance square', 'bitbucket', 'bitbucket square', 'bitcoin', 'buysellads', 'codepen', 'connectdevelop', 'dashcube', 'delicious', 'deviantart', 'digg', 'dribbble', 'dropbox', 'drupal', 'empire', 'facebook', 'facebook square', 'flickr', 'forumbee', 'foursquare', 'git', 'git square', 'github alternate', 'github', 'github square', 'gittip', 'google', 'google plus', 'google plus square', 'hacker news', 'instagram', 'ioxhost', 'joomla', 'jsfiddle', 'lastfm', 'lastfm square', 'leanpub', 'linkedin', 'linkedin square', 'linux', 'maxcdn', 'meanpath', 'medium', 'pagelines', 'pied piper alternate', 'pied piper', 'pinterest', 'pinterest square', 'qq', 'rebel', 'reddit', 'reddit square', 'renren', 'sellsy', 'shirtsinbulk', 'simplybuilt', 'skyatlas', 'skype', 'slack', 'slideshare', 'soundcloud', 'spotify', 'stack exchange', 'stack overflow', 'steam', 'steam square', 'stumbleupon circle', 'stumbleupon', 'tencent weibo', 'trello', 'tumblr', 'tumblr square', 'twitch', 'twitter', 'twitter square', 'viacoin', 'vimeo', 'vine', 'vk', 'wechat', 'weibo', 'whatsapp', 'windows', 'wordpress', 'xing', 'xing square', 'yahoo', 'yelp', 'youtube', 'youtube play', 'youtube squar'],
    autoform: {
      type: 'select',
      firstOption: true,
      options: function () {
        return [
          { label: 'Select an icon', value: 'noIcon'},
          { label: 'Add circle', value: 'add circle'},
          { label: 'Add square', value: 'add square'},
          { label: 'Add to cart', value: 'add to cart'},
          { label: 'Add user', value: 'add user'},
          { label: 'Adjust', value: 'adjust'},
          { label: 'Adn', value: 'adn'},
          { label: 'Alarm outline', value: 'alarm outline'},
          { label: 'Alarm slash outline', value: 'alarm slash outline'},
          { label: 'Alarm slash', value: 'alarm slash'},
          { label: 'Alarm', value: 'alarm'},
          { label: 'Align center', value: 'align center'},
          { label: 'Align justify', value: 'align justify'},
          { label: 'Align left', value: 'align left'},
          { label: 'Align right', value: 'align right'},
          { label: 'American express', value: 'american express'},
          { label: 'Anchor', value: 'anchor'},
          { label: 'Android', value: 'android'},
          { label: 'Angellist', value: 'angellist'},
          { label: 'Angle double down', value: 'angle double down'},
          { label: 'Angle double left', value: 'angle double left'},
          { label: 'Angle double right', value: 'angle double right'},
          { label: 'Angle double up', value: 'angle double up'},
          { label: 'Angle down', value: 'angle down'},
          { label: 'Angle left', value: 'angle left'},
          { label: 'Angle right', value: 'angle right'},
          { label: 'Angle up', value: 'angle up'},
          { label: 'Announcement', value: 'announcement'},
          { label: 'Apple', value: 'apple'},
          { label: 'Archive', value: 'archive'},
          { label: 'Area chart', value: 'area chart'},
          { label: 'Arrow circle down', value: 'arrow circle down'},
          { label: 'Arrow circle left', value: 'arrow circle left'},
          { label: 'Arrow circle outline down', value: 'arrow circle outline down'},
          { label: 'Arrow circle outline left', value: 'arrow circle outline left'},
          { label: 'Arrow circle outline right', value: 'arrow circle outline right'},
          { label: 'Arrow circle outline up', value: 'arrow circle outline up'},
          { label: 'Arrow circle right', value: 'arrow circle right'},
          { label: 'Arrow circle up', value: 'arrow circle up'},
          { label: 'Arrow down', value: 'arrow down'},
          { label: 'Arrow left', value: 'arrow left'},
          { label: 'Arrow right', value: 'arrow right'},
          { label: 'Arrow up', value: 'arrow up'},
          { label: 'Asterisk', value: 'asterisk'},
          { label: 'At', value: 'at'},
          { label: 'Attach', value: 'attach'},
          { label: 'Backward', value: 'backward'},
          { label: 'Ban', value: 'ban'},
          { label: 'Bar chart', value: 'bar chart'},
          { label: 'Bar', value: 'bar'},
          { label: 'Barcode', value: 'barcode'},
          { label: 'Behance square', value: 'behance square'},
          { label: 'Behance', value: 'behance'},
          { label: 'Birthday', value: 'birthday'},
          { label: 'Bitbucket square', value: 'bitbucket square'},
          { label: 'Bitbucket', value: 'bitbucket'},
          { label: 'Bitcoin', value: 'bitcoin'},
          { label: 'Block layout', value: 'block layout'},
          { label: 'Bold', value: 'bold'},
          { label: 'Bomb', value: 'bomb'},
          { label: 'Book', value: 'book'},
          { label: 'Bookmark', value: 'bookmark'},
          { label: 'Browser', value: 'browser'},
          { label: 'Bug', value: 'bug'},
          { label: 'Building outline', value: 'building outline'},
          { label: 'Building', value: 'building'},
          { label: 'Bullseye', value: 'bullseye'},
          { label: 'Buysellads', value: 'buysellads'},
          { label: 'Calculator', value: 'calculator'},
          { label: 'Calendar outline', value: 'calendar outline'},
          { label: 'Calendar', value: 'calendar'},
          { label: 'Call square', value: 'call square'},
          { label: 'Call', value: 'call'},
          { label: 'Camera retro', value: 'camera retro'},
          { label: 'Car', value: 'car'},
          { label: 'Caret down', value: 'caret down'},
          { label: 'Caret left', value: 'caret left'},
          { label: 'Caret right', value: 'caret right'},
          { label: 'Caret up', value: 'caret up'},
          { label: 'Certificate', value: 'certificate'},
          { label: 'Check circle outline', value: 'check circle outline'},
          { label: 'Check circle', value: 'check circle'},
          { label: 'Check square', value: 'check square'},
          { label: 'Checkered flag', value: 'checkered flag'},
          { label: 'Checkmark box', value: 'checkmark box'},
          { label: 'Checkmark', value: 'checkmark'},
          { label: 'Chevron circle down', value: 'chevron circle down'},
          { label: 'Chevron circle left', value: 'chevron circle left'},
          { label: 'Chevron circle right', value: 'chevron circle right'},
          { label: 'Chevron circle up', value: 'chevron circle up'},
          { label: 'Chevron down', value: 'chevron down'},
          { label: 'Chevron left', value: 'chevron left'},
          { label: 'Chevron right', value: 'chevron right'},
          { label: 'Chevron up', value: 'chevron up'},
          { label: 'Child', value: 'child'},
          { label: 'Circle notched', value: 'circle notched'},
          { label: 'Circle thin', value: 'circle thin'},
          { label: 'Circle', value: 'circle'},
          { label: 'Cloud download', value: 'cloud download'},
          { label: 'Cloud upload', value: 'cloud upload'},
          { label: 'Cloud', value: 'cloud'},
          { label: 'Cocktail', value: 'cocktail'},
          { label: 'Codepen', value: 'codepen'},
          { label: 'Coffee', value: 'coffee'},
          { label: 'Columns', value: 'columns'},
          { label: 'Comment outline', value: 'comment outline'},
          { label: 'Comment', value: 'comment'},
          { label: 'Comments outline', value: 'comments outline'},
          { label: 'Comments', value: 'comments'},
          { label: 'Compress', value: 'compress'},
          { label: 'Configure', value: 'configure'},
          { label: 'Connectdevelop', value: 'connectdevelop'},
          { label: 'Copy', value: 'copy'},
          { label: 'Copyright', value: 'copyright'},
          { label: 'Crop', value: 'crop'},
          { label: 'Crosshairs', value: 'crosshairs'},
          { label: 'Css3', value: 'css3'},
          { label: 'Cube', value: 'cube'},
          { label: 'Cubes', value: 'cubes'},
          { label: 'Cut', value: 'cut'},
          { label: 'Dashboard', value: 'dashboard'},
          { label: 'Dashcube', value: 'dashcube'},
          { label: 'Database', value: 'database'},
          { label: 'Delicious', value: 'delicious'},
          { label: 'Desktop', value: 'desktop'},
          { label: 'Deviantart', value: 'deviantart'},
          { label: 'Diamond', value: 'diamond'},
          { label: 'Digg', value: 'digg'},
          { label: 'Discover', value: 'discover'},
          { label: 'Disk outline', value: 'disk outline'},
          { label: 'Doctor', value: 'doctor'},
          { label: 'Dollar', value: 'dollar'},
          { label: 'Download', value: 'download'},
          { label: 'Dribbble', value: 'dribbble'},
          { label: 'Dropbox', value: 'dropbox'},
          { label: 'Dropdown', value: 'dropdown'},
          { label: 'Drupal', value: 'drupal'},
          { label: 'Edit', value: 'edit'},
          { label: 'Eject', value: 'eject'},
          { label: 'Ellipsis horizontal', value: 'ellipsis horizontal'},
          { label: 'Ellipsis vertical', value: 'ellipsis vertical'},
          { label: 'Emergency', value: 'emergency'},
          { label: 'Empire', value: 'empire'},
          { label: 'Empty heart', value: 'empty heart'},
          { label: 'Empty star', value: 'empty star'},
          { label: 'Erase', value: 'erase'},
          { label: 'Euro', value: 'euro'},
          { label: 'Exchange', value: 'exchange'},
          { label: 'Expand', value: 'expand'},
          { label: 'External share', value: 'external share'},
          { label: 'External square', value: 'external square'},
          { label: 'External', value: 'external'},
          { label: 'Eyedropper', value: 'eyedropper'},
          { label: 'Facebook square', value: 'facebook square'},
          { label: 'Facebook', value: 'facebook'},
          { label: 'Fast backward', value: 'fast backward'},
          { label: 'Fast forward', value: 'fast forward'},
          { label: 'Fax', value: 'fax'},
          { label: 'Feed', value: 'feed'},
          { label: 'Female', value: 'female'},
          { label: 'File archive outline', value: 'file archive outline'},
          { label: 'File audio outline', value: 'file audio outline'},
          { label: 'File code outline', value: 'file code outline'},
          { label: 'File excel outline', value: 'file excel outline'},
          { label: 'File image outline', value: 'file image outline'},
          { label: 'File outline', value: 'file outline'},
          { label: 'File pdf outline', value: 'file pdf outline'},
          { label: 'File powerpoint outline', value: 'file powerpoint outline'},
          { label: 'File text outline', value: 'file text outline'},
          { label: 'File text', value: 'file text'},
          { label: 'File video outline', value: 'file video outline'},
          { label: 'File word outline', value: 'file word outline'},
          { label: 'File', value: 'file'},
          { label: 'Film', value: 'film'},
          { label: 'Filter', value: 'filter'},
          { label: 'Find', value: 'find'},
          { label: 'Fire extinguisher', value: 'fire extinguisher'},
          { label: 'Fire', value: 'fire'},
          { label: 'First aid', value: 'first aid'},
          { label: 'Flag outline', value: 'flag outline'},
          { label: 'Flag', value: 'flag'},
          { label: 'Flickr', value: 'flickr'},
          { label: 'Folder open outline', value: 'folder open outline'},
          { label: 'Folder open', value: 'folder open'},
          { label: 'Folder outline', value: 'folder outline'},
          { label: 'Folder', value: 'folder'},
          { label: 'Font', value: 'font'},
          { label: 'Food', value: 'food'},
          { label: 'Fork', value: 'fork'},
          { label: 'Forumbee', value: 'forumbee'},
          { label: 'Forward mail', value: 'forward mail'},
          { label: 'Forward', value: 'forward'},
          { label: 'Foursquare', value: 'foursquare'},
          { label: 'Frown', value: 'frown'},
          { label: 'Game', value: 'game'},
          { label: 'Gay', value: 'gay'},
          { label: 'Gift', value: 'gift'},
          { label: 'Git square', value: 'git square'},
          { label: 'Git', value: 'git'},
          { label: 'Github alternate', value: 'github alternate'},
          { label: 'Github square', value: 'github square'},
          { label: 'Github', value: 'github'},
          { label: 'Gittip', value: 'gittip'},
          { label: 'Google plus square', value: 'google plus square'},
          { label: 'Google plus', value: 'google plus'},
          { label: 'Google wallet', value: 'google wallet'},
          { label: 'Google', value: 'google'},
          { label: 'Grid layout', value: 'grid layout'},
          { label: 'H', value: 'h'},
          { label: 'Hacker news', value: 'hacker news'},
          { label: 'Handicap', value: 'handicap'},
          { label: 'Header', value: 'header'},
          { label: 'Heart', value: 'heart'},
          { label: 'Heartbeat', value: 'heartbeat'},
          { label: 'Help circle', value: 'help circle'},
          { label: 'Help', value: 'help'},
          { label: 'Heterosexual', value: 'heterosexual'},
          { label: 'Hide', value: 'hide'},
          { label: 'History', value: 'history'},
          { label: 'Home', value: 'home'},
          { label: 'Hospital', value: 'hospital'},
          { label: 'Html5', value: 'html5'},
          { label: 'Idea', value: 'idea'},
          { label: 'In cart', value: 'in cart'},
          { label: 'Inbox', value: 'inbox'},
          { label: 'Indent', value: 'indent'},
          { label: 'Info circle', value: 'info circle'},
          { label: 'Info', value: 'info'},
          { label: 'Instagram', value: 'instagram'},
          { label: 'Intergender', value: 'intergender'},
          { label: 'Ioxhost', value: 'ioxhost'},
          { label: 'Italic', value: 'italic'},
          { label: 'Joomla', value: 'joomla'},
          { label: 'Jsfiddle', value: 'jsfiddle'},
          { label: 'Keyboard', value: 'keyboard'},
          { label: 'Lab', value: 'lab'},
          { label: 'Laptop', value: 'laptop'},
          { label: 'Lastfm square', value: 'lastfm square'},
          { label: 'Lastfm', value: 'lastfm'},
          { label: 'Leaf', value: 'leaf'},
          { label: 'Leanpub', value: 'leanpub'},
          { label: 'Legal', value: 'legal'},
          { label: 'Lemon', value: 'lemon'},
          { label: 'Lesbian', value: 'lesbian'},
          { label: 'Level down', value: 'level down'},
          { label: 'Level up', value: 'level up'},
          { label: 'Life ring', value: 'life ring'},
          { label: 'Lightning', value: 'lightning'},
          { label: 'Line chart', value: 'line chart'},
          { label: 'Linkedin square', value: 'linkedin square'},
          { label: 'Linkedin', value: 'linkedin'},
          { label: 'Linkify', value: 'linkify'},
          { label: 'Linux', value: 'linux'},
          { label: 'Lira', value: 'lira'},
          { label: 'List layout', value: 'list layout'},
          { label: 'List', value: 'list'},
          { label: 'Location arrow', value: 'location arrow'},
          { label: 'Lock', value: 'lock'},
          { label: 'Long arrow down', value: 'long arrow down'},
          { label: 'Long arrow left', value: 'long arrow left'},
          { label: 'Long arrow right', value: 'long arrow right'},
          { label: 'Long arrow up', value: 'long arrow up'},
          { label: 'Magnet', value: 'magnet'},
          { label: 'Mail outline', value: 'mail outline'},
          { label: 'Mail square', value: 'mail square'},
          { label: 'Mail', value: 'mail'},
          { label: 'Male', value: 'male'},
          { label: 'Man', value: 'man'},
          { label: 'Map', value: 'map'},
          { label: 'Marker', value: 'marker'},
          { label: 'Mastercard', value: 'mastercard'},
          { label: 'Maxcdn', value: 'maxcdn'},
          { label: 'Maximize', value: 'maximize'},
          { label: 'Meanpath', value: 'meanpath'},
          { label: 'Medium', value: 'medium'},
          { label: 'Meh', value: 'meh'},
          { label: 'Military', value: 'military'},
          { label: 'Minus circle', value: 'minus circle'},
          { label: 'Minus square outline', value: 'minus square outline'},
          { label: 'Minus square', value: 'minus square'},
          { label: 'Minus', value: 'minus'},
          { label: 'Mobile', value: 'mobile'},
          { label: 'Money', value: 'money'},
          { label: 'Moon', value: 'moon'},
          { label: 'Move', value: 'move'},
          { label: 'Music', value: 'music'},
          { label: 'Mute', value: 'mute'},
          { label: 'Neuter', value: 'neuter'},
          { label: 'Newspaper', value: 'newspaper'},
          { label: 'Non binary transgender', value: 'non binary transgender'},
          { label: 'Openid', value: 'openid'},
          { label: 'Options', value: 'options'},
          { label: 'Ordered list', value: 'ordered list'},
          { label: 'Other gender horizontal', value: 'other gender horizontal'},
          { label: 'Other gender vertical', value: 'other gender vertical'},
          { label: 'Other gender', value: 'other gender'},
          { label: 'Outdent', value: 'outdent'},
          { label: 'Pagelines', value: 'pagelines'},
          { label: 'Paint brush', value: 'paint brush'},
          { label: 'Paragraph', value: 'paragraph'},
          { label: 'Paste', value: 'paste'},
          { label: 'Pause', value: 'pause'},
          { label: 'Paw', value: 'paw'},
          { label: 'Payment', value: 'payment'},
          { label: 'Paypal card', value: 'paypal card'},
          { label: 'Paypal', value: 'paypal'},
          { label: 'Phone square', value: 'phone square'},
          { label: 'Phone', value: 'phone'},
          { label: 'Photo', value: 'photo'},
          { label: 'Pie chart', value: 'pie chart'},
          { label: 'Pied piper alternate', value: 'pied piper alternate'},
          { label: 'Pied piper', value: 'pied piper'},
          { label: 'Pin', value: 'pin'},
          { label: 'Pinterest square', value: 'pinterest square'},
          { label: 'Pinterest', value: 'pinterest'},
          { label: 'Plane', value: 'plane'},
          { label: 'Play', value: 'play'},
          { label: 'Plug', value: 'plug'},
          { label: 'Plus square outline', value: 'plus square outline'},
          { label: 'Plus', value: 'plus'},
          { label: 'Pointing down', value: 'pointing down'},
          { label: 'Pointing left', value: 'pointing left'},
          { label: 'Pointing right', value: 'pointing right'},
          { label: 'Pointing up', value: 'pointing up'},
          { label: 'Pound', value: 'pound'},
          { label: 'Power', value: 'power'},
          { label: 'Print', value: 'print'},
          { label: 'Privacy', value: 'privacy'},
          { label: 'Protect', value: 'protect'},
          { label: 'Puzzle', value: 'puzzle'},
          { label: 'Qq', value: 'qq'},
          { label: 'Qrcode', value: 'qrcode'},
          { label: 'Quote left', value: 'quote left'},
          { label: 'Quote right', value: 'quote right'},
          { label: 'Radio', value: 'radio'},
          { label: 'Rain', value: 'rain'},
          { label: 'Random', value: 'random'},
          { label: 'Rebel', value: 'rebel'},
          { label: 'Record', value: 'record'},
          { label: 'Recycle', value: 'recycle'},
          { label: 'Reddit square', value: 'reddit square'},
          { label: 'Reddit', value: 'reddit'},
          { label: 'Refresh', value: 'refresh'},
          { label: 'Remove bookmark', value: 'remove bookmark'},
          { label: 'Remove circle outline', value: 'remove circle outline'},
          { label: 'Remove circle', value: 'remove circle'},
          { label: 'Remove user', value: 'remove user'},
          { label: 'Remove', value: 'remove'},
          { label: 'Renren', value: 'renren'},
          { label: 'Repeat', value: 'repeat'},
          { label: 'Reply all', value: 'reply all'},
          { label: 'Reply', value: 'reply'},
          { label: 'Resize horizontal', value: 'resize horizontal'},
          { label: 'Resize vertical', value: 'resize vertical'},
          { label: 'Retweet', value: 'retweet'},
          { label: 'Road', value: 'road'},
          { label: 'Rocket', value: 'rocket'},
          { label: 'Rss square', value: 'rss square'},
          { label: 'Rss', value: 'rss'},
          { label: 'Ruble', value: 'ruble'},
          { label: 'Rupee', value: 'rupee'},
          { label: 'Save', value: 'save'},
          { label: 'Search', value: 'search'},
          { label: 'Selected radio', value: 'selected radio'},
          { label: 'Sellsy', value: 'sellsy'},
          { label: 'Send outline', value: 'send outline'},
          { label: 'Send', value: 'send'},
          { label: 'Server', value: 'server'},
          { label: 'Setting', value: 'setting'},
          { label: 'Settings', value: 'settings'},
          { label: 'Share alternate square', value: 'share alternate square'},
          { label: 'Share alternate', value: 'share alternate'},
          { label: 'Share square', value: 'share square'},
          { label: 'Share', value: 'share'},
          { label: 'Shekel', value: 'shekel'},
          { label: 'Shipping', value: 'shipping'},
          { label: 'Shirtsinbulk', value: 'shirtsinbulk'},
          { label: 'Shop', value: 'shop'},
          { label: 'Sidebar', value: 'sidebar'},
          { label: 'Sign in', value: 'sign in'},
          { label: 'Sign out', value: 'sign out'},
          { label: 'Signal', value: 'signal'},
          { label: 'Simplybuilt', value: 'simplybuilt'},
          { label: 'Sitemap', value: 'sitemap'},
          { label: 'Skyatlas', value: 'skyatlas'},
          { label: 'Skype', value: 'skype'},
          { label: 'Slack', value: 'slack'},
          { label: 'Slideshare', value: 'slideshare'},
          { label: 'Smile', value: 'smile'},
          { label: 'Soccer', value: 'soccer'},
          { label: 'Sort alphabet ascending', value: 'sort alphabet ascending'},
          { label: 'Sort alphabet descending', value: 'sort alphabet descending'},
          { label: 'Sort ascending', value: 'sort ascending'},
          { label: 'Sort content ascending', value: 'sort content ascending'},
          { label: 'Sort content descending', value: 'sort content descending'},
          { label: 'Sort descending', value: 'sort descending'},
          { label: 'Sort numeric ascending', value: 'sort numeric ascending'},
          { label: 'Sort numeric descending', value: 'sort numeric descending'},
          { label: 'Sort', value: 'sort'},
          { label: 'Sound', value: 'sound'},
          { label: 'Soundcloud', value: 'soundcloud'},
          { label: 'Space shuttle', value: 'space shuttle'},
          { label: 'Spinner', value: 'spinner'},
          { label: 'Spoon', value: 'spoon'},
          { label: 'Spotify', value: 'spotify'},
          { label: 'Spy', value: 'spy'},
          { label: 'Square outline', value: 'square outline'},
          { label: 'Square', value: 'square'},
          { label: 'Stack exchange', value: 'stack exchange'},
          { label: 'Stack overflow', value: 'stack overflow'},
          { label: 'Star half empty', value: 'star half empty'},
          { label: 'Star half', value: 'star half'},
          { label: 'Star', value: 'star'},
          { label: 'Steam square', value: 'steam square'},
          { label: 'Steam', value: 'steam'},
          { label: 'Step backward', value: 'step backward'},
          { label: 'Step forward', value: 'step forward'},
          { label: 'Stop', value: 'stop'},
          { label: 'Strikethrough', value: 'strikethrough'},
          { label: 'Stripe', value: 'stripe'},
          { label: 'Student', value: 'student'},
          { label: 'Stumbleupon circle', value: 'stumbleupon circle'},
          { label: 'Stumbleupon', value: 'stumbleupon'},
          { label: 'Subscript', value: 'subscript'},
          { label: 'Suitcase', value: 'suitcase'},
          { label: 'Sun', value: 'sun'},
          { label: 'Superscript', value: 'superscript'},
          { label: 'Table', value: 'table'},
          { label: 'Tablet', value: 'tablet'},
          { label: 'Tag', value: 'tag'},
          { label: 'Tags', value: 'tags'},
          { label: 'Tasks', value: 'tasks'},
          { label: 'Taxi', value: 'taxi'},
          { label: 'Tencent weibo', value: 'tencent weibo'},
          { label: 'Terminal', value: 'terminal'},
          { label: 'Text height', value: 'text height'},
          { label: 'Text telephone', value: 'text telephone'},
          { label: 'Text width', value: 'text width'},
          { label: 'Theme', value: 'theme'},
          { label: 'Thumbs down', value: 'thumbs down'},
          { label: 'Thumbs outline down', value: 'thumbs outline down'},
          { label: 'Thumbs outline up', value: 'thumbs outline up'},
          { label: 'Thumbs up', value: 'thumbs up'},
          { label: 'Ticket', value: 'ticket'},
          { label: 'Toggle down', value: 'toggle down'},
          { label: 'Toggle left', value: 'toggle left'},
          { label: 'Toggle off', value: 'toggle off'},
          { label: 'Toggle on', value: 'toggle on'},
          { label: 'Toggle right', value: 'toggle right'},
          { label: 'Toggle up', value: 'toggle up'},
          { label: 'Transgender', value: 'transgender'},
          { label: 'Translate', value: 'translate'},
          { label: 'Trash outline', value: 'trash outline'},
          { label: 'Trash', value: 'trash'},
          { label: 'Travel', value: 'travel'},
          { label: 'Treatment', value: 'treatment'},
          { label: 'Tree', value: 'tree'},
          { label: 'Trello', value: 'trello'},
          { label: 'Trophy', value: 'trophy'},
          { label: 'Tumblr square', value: 'tumblr square'},
          { label: 'Tumblr', value: 'tumblr'},
          { label: 'Twitch', value: 'twitch'},
          { label: 'Twitter square', value: 'twitter square'},
          { label: 'Twitter', value: 'twitter'},
          { label: 'Underline', value: 'underline'},
          { label: 'Undo', value: 'undo'},
          { label: 'Unhide', value: 'unhide'},
          { label: 'University', value: 'university'},
          { label: 'Unlink', value: 'unlink'},
          { label: 'Unlock alternate', value: 'unlock alternate'},
          { label: 'Unlock', value: 'unlock'},
          { label: 'Unmute', value: 'unmute'},
          { label: 'Unordered list', value: 'unordered list'},
          { label: 'Upload', value: 'upload'},
          { label: 'User', value: 'user'},
          { label: 'Users', value: 'users'},
          { label: 'Viacoin', value: 'viacoin'},
          { label: 'Video play outline', value: 'video play outline'},
          { label: 'Video play', value: 'video play'},
          { label: 'Vimeo', value: 'vimeo'},
          { label: 'Vine', value: 'vine'},
          { label: 'Visa', value: 'visa'},
          { label: 'Vk', value: 'vk'},
          { label: 'Volume down', value: 'volume down'},
          { label: 'Volume off', value: 'volume off'},
          { label: 'Volume up', value: 'volume up'},
          { label: 'Wait', value: 'wait'},
          { label: 'Warning circle', value: 'warning circle'},
          { label: 'Warning sign', value: 'warning sign'},
          { label: 'Warning', value: 'warning'},
          { label: 'Wechat', value: 'wechat'},
          { label: 'Weibo', value: 'weibo'},
          { label: 'Whatsapp', value: 'whatsapp'},
          { label: 'Wifi', value: 'wifi'},
          { label: 'Windows', value: 'windows'},
          { label: 'Wizard', value: 'wizard'},
          { label: 'Woman', value: 'woman'},
          { label: 'Won', value: 'won'},
          { label: 'Wordpress', value: 'wordpress'},
          { label: 'World', value: 'world'},
          { label: 'Write square', value: 'write square'},
          { label: 'Write', value: 'write'},
          { label: 'Xing square', value: 'xing square'},
          { label: 'Xing', value: 'xing'},
          { label: 'Yahoo', value: 'yahoo'},
          { label: 'Yelp', value: 'yelp'},
          { label: 'Yen', value: 'yen'},
          { label: 'Youtube play', value: 'youtube play'},
          { label: 'Youtube square', value: 'youtube squar'},
          { label: 'Youtube', value: 'youtube'},
          { label: 'Zoom out', value: 'zoom out'},
          { label: 'Zoom', value: 'zoom'},
        ];
      }
    }
  },
  color: {
    type: String,
    label: 'Button color',
    optional: true,
    allowedValues: ['red', 'orange', 'yellow', 'olive', 'green', 'teal', 'blue', 'violet', 'purple', 'pink', 'brown', 'grey', 'black'],
    autoform: {
      type: 'select',
      firstOption: true,
      options: function () {
        return [
          {value: 'noColor', label: 'Select a color' },
          {value: 'black', label: 'Black' },
          {value: 'blue', label: 'Blue' },
          {value: 'brown', label: 'Brown' },
          {value: 'green', label: 'Green' },
          {value: 'grey', label: 'Grey' },
          {value: 'olive', label: 'Olive' },
          {value: 'orange', label: 'Orange' },
          {value: 'pink', label: 'Pink' },
          {value: 'purple', label: 'Purple' },
          {value: 'red', label: 'Red' },
          {value: 'teal', label: 'Teal' },
          {value: 'violet', label: 'Violet' },
          {value: 'yellow', label: 'Yellow' },
        ];
      }
    }
  },
  description: {
    type: String,
    label: 'Button description',
    optional: true
  },
  clicks: {
    type: Number,
    label: 'Clicks counter',
    optional: true,
    autoform: {
      omit: true
    },
    autoValue: function () {
      if (this.isInsert) {
        return 0;
      }
    }
  },
  owners: {
    type: [String],
    regEx: SimpleSchema.RegEx.Id,
    autoform: {
      type: 'hidden',
      label: false
    },
    autoValue: function () { if (this.isInsert) { return [this.userId]; }}
  },
  users: {
    type: [String],
    regEx: SimpleSchema.RegEx.Id,
    optional: true,
    autoform: {
      type: 'hidden',
      label: false
    }
  },
  isPublic: {
    type: Boolean,
    label: 'Public button',
    optional: true,
    autoValue: function () {
      if (this.isInsert) {
        return false;
      }
    }
  },
  createdAt: {
    type: Date,
    autoValue: function () {
      if (this.isInsert) {
        return new Date();
      } else if (this.isUpsert) {
        return {$setOnInsert: new Date()};
      } else {
        this.unset();
      }
    },
    autoform: {
      omit: true
    }
  },
  updatedAt: {
    type: Date,
    autoValue: function () {
      if (this.isUpdate) {
        return new Date();
      }
    },
    denyInsert: true,
    optional: true,
    autoform: {
      omit: true
    }
  }
});

Items.attachSchema(ItemsSchema);
